variable "network_interface_name" {}
variable "network_interface_location" {}
variable "network_interface_resource_group_name" {}
variable "virtual_machine_name" {}
variable "virtual_machine_resource_group_name" {}
variable "virtual_machine_location" {}
variable "virtual_machine_size" {}
variable "virtual_machine_admin_username" {}
variable "virtual_machine_admin_password" {}
variable "subnet_name" {}
variable "subnet_virtual_network_name" {}
variable "subnet_resource_group_name" {}
variable "public_ip_name" {}
variable "public_ip_resource_group_name" {}
variable "network_security_group_name" {}
variable "network_security_group_resource_group_name" {}
variable "key_vault_name" {}
variable "key_vault_resource_group_name" {}
variable "vm_username_secret_name" {}
variable "vm_password_secret_name" {}